baseurl = "https://impractical.engineering"
pygmentsuseclasses = true
title = "Impractical Engineering"

[params]
description = "Bad ideas from impractical people."
logo = "logo.svg"

[permalinks]
post = "/:title"
